title: Guanxi Jiang
email: 2429648J@student.gla.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Guanxi Jiang, UESTC.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  GuanxiJiang # DO NOT include the @ character, or else the build will fail!

avatar: "https://github.com/GuanxiJiang/GuanxiJiang.github.io/blob/main/gxj.jpg"
